### ISSUE TITLE
Image feature extractor

### ISSUE THREAD

**Issue by OneDirection9** [vmurahari3/visdial-diversity#1]
Hi,

awesome work and thanks for sharing the code.

I am confused about which model is used to extract image features, VGG-19 or VGG-16?

```
# Processed image features for VisDial v1.0, using **VGG-19**
wget https://s3.amazonaws.com/visual-dialog/data/v1.0/data_img_**vgg16**_relu7_train.h5 -O data/visdial/data_img.h5
```

The comment line says it is **VGG19**, but the URL says it is **VGG16**.

Besides, do the released models downloaded by `download_checkpoints.sh` are trained by the data downloaded by `download_preprocessed.sh`?

Thanks!

**Comment by vmurahari3** [comment]
That is a mistake on my end. VGG-16 is used to calculate the features.

Yes, the released models are trained on data downloaded by `download_preprocessed.sh`

**Comment by OneDirection9** [comment]
Got it. Thanks!
