### ISSUE TITLE
What should be provided for the -cocoDir and -cocoInfo flags?

### ISSUE THREAD

**Issue by JackFurby** [vmurahari3/visdial-diversity#2]
Hello,

I have set up this repo on my local machine but am confused by what I should provide for the flags -cocoDir and -cocoInfo for training. I am assuming -cocoDir points to a directory containing the coco dataset, but for -cocoInfo I cannot find a suitable JSON file from the dataset itself or if/how I generate a new JSON file.

Thanks,
Jack

**Comment by JackFurby** [comment]
I have also made the assumption the 2017 dataset split will work. Is this correct or should I be using the 2014 dataset split

**Comment by JackFurby** [comment]
I think I have found a solution. I made a small script to generate a `coco.json` file that seems to be working. This can be found here: https://gist.github.com/JackFurby/249c5f584c2df4dda80361af5b05a368

**Comment by vmurahari3** [comment]
Hey, 

Please use the 2014 split. When you download the dataset, you should have a `coco.json` file inside I think. For `cocoDir` please use  << coco root dir >>/images .

**Comment by JackFurby** [comment]
Thank you @vmurahari3 for confirming the correct dataset split to use and how to correctly use the flags. I still cannot find the provided `coco.json` file. Perhaps it is no longer included in the dataset? I don't think that will be an issue though.
